### PR TITLE
feat: support `status` fn for StatusManager

### PR DESCRIPTION
**Pull request by greenhat616**
Close https://github.com/chipsenkbeil/service-manager-rs/issues/5

use a enum `ServiceStatus` to represent the services state:

```rust
pub enum ServiceStatus {
    NotInstalled,
    Running,
    Stopped(Option<String>), // Provide a reason if possible
}
```

* [x] finish all related managers
* [x] add test suits
* [x] add decoding support for among differnet windows code page

### CODE REVIEW

**Comment by greenhat616** [comment]
@jacderida Ready to CI run. Thx

**Comment by chipsenkbeil** [comment]
I just realized this has been sitting here. @jacderida @greenhat616 this is something ready for review?

**Comment by greenhat616** [comment]
@chipsenkbeil Hi. I think it is ready for review, and i have use this patch in https://github.com/LibNyanpasu/nyanpasu-service.

I have manually test the all platform expect the `rc.d` which I don't own the test environment.

**Comment by chipsenkbeil** [comment]
@greenhat616 hm, I'm not sure why the automated tests aren't running. The button for me to trigger them seems to be missing.

I'll take a look at running manually this weekend and get this merged in. Sorry for waiting so long!

**Comment by chipsenkbeil** [comment]
@greenhat616 ran parts of it this weekend. Going to merge and anything that needs to change before the next release can sneak in over the week.

Thanks again for the PR!

**Pull request merged**
