### PR TITLE
WinSW uninstall deletes service directories

### PR DESCRIPTION
**Pull request by jacderida**
With the WinSW service manager, each service definition has its own directory. In addition to the service definition, WinSW also produces logs that get output to this directory. In our product, we frequently create and delete services with the same names, so we found it problematic for these directories to remain around.

The service manager is now updated to delete the service directory upon uninstall.

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
I'm in London until tomorrow. So this weekend 😄

**Comment by jacderida** [comment]
Cool, thanks!

**Comment by chipsenkbeil** [comment]
> Cool, thanks!

Released now: https://github.com/chipsenkbeil/service-manager-rs/releases/tag/v0.6.2

**Comment by jacderida** [comment]
Awesome, thank you! I may have another PR coming shortly...

**Pull request merged**
